language: objective-c
osx_image: xcode12

xcode_workspace: ./Example/PutioAPI.xcworkspace
xcode_scheme: PutioAPI-Example
xcode_destination: platform=iOS Simulator,OS=14.0,name=iPhone 11

deploy:
  provider: script
  script: ./scripts/push.sh
  on:
    tags: true
